[mypy]
python_version = 3.10
ignore_missing_imports = True
warn_unused_ignores = False
warn_return_any = False
strict_optional = True

[mypy-dask.*]
ignore_missing_imports = True

[mypy-distributed.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-tenacity.*]
ignore_missing_imports = True
